{{- if and (index .Values "kube-audit-rest") (index .Values "kube-audit-rest" "enable") -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.destinationServer}}-kube-audit-rest
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: clusters/{{ .Values.clusterName }}/addons/kube-audit-rest
    targetRevision: {{ .Values.targetRevision }}
    helm:
      releaseName: kube-audit-rest
  destination:
    name: {{ .Values.destinationServer | default "in-cluster" }}
    namespace: {{ index .Values "kube-audit-rest" "namespace" }}
  syncPolicy:
    syncOptions:
      - CreateNamespace={{ index .Values "kube-audit-rest" "createNamespace" }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
