apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: https
    - name: metrics
      port: {{ .Values.metricsPort }}
      protocol: TCP
      targetPort: metrics
  selector:
    app: {{ .Release.Name }}
