apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    {{- if .Values.tls.certManager.enabled }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Release.Name }}-tls
    {{- end }}
webhooks:
  - name: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    sideEffects: None
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ .Release.Name }}
        namespace: {{ .Release.Namespace }}
        path: "/log-request"
    rules:
      {{- toYaml .Values.webhook.rules | nindent 6 }}
