{{ if and .Values.oidc.enabled .Values.eso.enabled }}
{{- $secretPath := .Values.eso.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-client-vault-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}
  data:
  - secretKey: clientSecret
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $secretPath }}
      property: vaultOIDC.oidcClientSecret
{{ end }}
