{{- if .Values.eso.enabled }}
{{- $secretPath := .Values.eso.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}
  data:
  - secretKey: username
    remoteRef:
      key: {{ $secretPath }}
      property: keycloak-admin-creds.username
  - secretKey: password
    remoteRef:
      key: {{ $secretPath }}
      property: keycloak-admin-creds.password
{{- end }}
