apiVersion: v2
name: argo-cd
description: A Helm chart for Argo CD Install

version: 10.6.0

appVersion: "v3.5.2"

dependencies:
- name: argo-cd
  version: 10.6.0
  repository: https://argoproj.github.io/argo-helm
