{{- if .Values.eso.enabled }}
{{- $secretPath := .Values.eso.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: krakend
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}
  target:
    name: krakend
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $secretPath }}
{{- end }}
