{{- if .Values.eso.enabled }}
{{- if .Values.atlantis.basicAuthSecretName -}}
{{- $secretName := .Values.eso.secretName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlantis-creds
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $secretName }}
        metadataPolicy: None
        property: username
      secretKey: username
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $secretName }}
        metadataPolicy: None
        property: password
      secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.eso.secretStoreName }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
{{- end }}
{{- end }}
