{{- if and .Values.eso.enabled .Values.saml.enabled }}
{{- $secretPath := .Values.eso.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-client-report-portal-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}
  data:
    - secretKey: clientSecret
      remoteRef:
        key: {{ $secretPath }}
        property: reportportal.clientSecret
{{- end }}
