{{ if .Values.eso.enabled }}
{{- $secretPath := .Values.eso.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: reportportal-postgresql-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}
  data:
  - secretKey: postgresql-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $secretPath }}
      metadataPolicy: None
      property: reportportal.postgresql-password
  - secretKey: postgresql-postgres-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $secretPath }}
      metadataPolicy: None
      property: reportportal.postgresql-postgres-password
{{ end }}
