{{- if .Values.eso.enabled }}
{{- if .Values.broker.create -}}
{{- $secretPath := .Values.eso.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-client-shared-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}
  data:
  - secretKey: clientSecret
    remoteRef:
      key: {{ $secretPath }}
      property: keycloak-client-shared-secret.clientSecret
{{- end }}
{{ end }}