{{- if .Values.eso.enabled }}
{{- $secretPath := .Values.eso.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ci-sonar
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}
  data:
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $secretPath }}
      metadataPolicy: None
      property: sonarqube-ci-user.password
{{- end }}
