{{ if .Values.eso.enabled }}
{{- $secretPath := .Values.eso.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awx-admin-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}
  data:
    - secretKey: password
      remoteRef:
        key: {{ $secretPath }}
        property: awx-operator.admin-password
{{- end }}
