{{- if .Values.eso.enabled }}
{{- $secretPath := .Values.eso.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-admin-ui
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}
  data:
  - secretKey: root-user
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $secretPath }}
      metadataPolicy: None
      property: minio.ROOT_USER
  - secretKey: root-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $secretPath }}
      metadataPolicy: None
      property: minio.ROOT_PASSWORD
{{- end }}
