{{ if .Values.eso.enabled }}
{{- $secretPath := .Values.eso.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-s3
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}
  data:
  - secretKey: REGISTRY_STORAGE_S3_ACCESSKEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $secretPath }}
      metadataPolicy: None
      property: s3-user.ACCESSKEY
  - secretKey: REGISTRY_STORAGE_S3_SECRETKEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $secretPath }}
      metadataPolicy: None
      property: s3-user.SECRETKEY
{{ end }}
