{{ if .Values.eso.enabled }}
{{- $secretPath := .Values.eso.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: defectdojo-redis-specific
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}
  data:
    - secretKey: redis-password
      remoteRef:
        key: {{ $secretPath }}
        property: defectdojo.redis-password
{{ end }}
